#ifndef CONFIG_H_
#define CONFIG_H_

// TODO(#1085): PLAYER_DEATH_LEVEL is hardcoded
//   Should be customizable in the Level Editor
#define PLAYER_DEATH_LEVEL 1000.0f

#define SOUND_SAMPLES_DEFAULT_VOLUME 80.0f

#define LEVEL_EDITOR_DETH_LEVEL_COLOR hsla(0.0f, 0.8f, 0.6f, 1.0f)

#define BACKGROUND_LAYERS_COUNT 3
#define BACKGROUND_LAYERS_STEP 0.2f
#define BACKGROUND_TURDS_PER_CHUNK 5
#define BACKGROUND_CHUNK_WIDTH 500.0f
#define BACKGROUND_CHUNK_HEIGHT 500.0f

#define ENTITY_MAX_ID_SIZE 36

#define SNAPPING_THRESHOLD 10.0f

#define CAMERA_RATIO_X 16.0f
#define CAMERA_RATIO_Y 9.0f

#define METADATA_TITLE_MAX_SIZE 256
#define METADATA_VERSION_MAX_SIZE 256
#define METADATA_FILEPATH_MAX_SIZE 512

#define VERSION "2"

// #define RENDERER_CONFIG SDL_RENDERER_SOFTWARE
#define RENDERER_CONFIG (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC)

#define UNDO_HISTORY_CAPACITY 256

#define EDIT_FIELD_CAPACITY 256

#define TMPMEM_CAPACITY (640 * KILO)

#define LEVEL_EDITOR_MEMORY_CAPACITY (640 * KILO)

#endif  // CONFIG_H_
